#!/bin/bash

host=bzr+ssh://ildjit@rugen.eecs.harvard.edu/home/ildjit/bzr

for i in `cat listOfAllModules`
do
	if ! test -d $i ; then
		echo "Branching $i"
		bzr branch $host/$i
		continue ;
	fi
	cd $i
	if test -d .bzr ; then
		echo "Merging $i"
		bzr merge $host/$i
	fi
	cd ..
done
echo All done
