.TH ILJIT-GC-COPY "December 01 2007"
.SH NAME
iljit-gc-copy \- This is a copy garbage collector for iljit dynamic compiler
.SH DESCRIPTION
iljit-gc-copy is a plugin of iljit dynamic compiler that implements a simple
copy garbage collector. Main documentation is located in your system
documentation directory as doxygen html files.
.SH SEE ALSO
.BR iljit (1),
.BR ildjit (1)
.SH AUTHOR
Speziale Ettore <speziale.ettore@gmail.com>
